### ISSUE TITLE
Compilation for WebAssembly

### ISSUE THREAD

**Issue by Arthi-chaud** [AnonymusRaccoon/Bomberman#73]

**Comment by AnonymusRaccoon** [comment]
If you want to implement it, check [that](https://github.com/raysan5/raylib/blob/master/examples/core/core_basic_window_web.c) (warning the WAL's loop has a fixed update depending on std::chrone. It may need to be reworked to fix that)

**Comment by AnonymusRaccoon** [comment]
Check with ThreeJS, they both have a FixedUpdate and an Update.
